name: my_mart
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1

  cupertino_icons: ^1.0.2
  google_sign_in: ^5.2.4
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: SupermercadoOne
      fonts:
        - asset: assets/fonts/SupermercadoOne-Regular.ttf
    
    - family: Rowdies
      fonts:
        - asset: assets/fonts/Rowdies-Regular.ttf
        - asset: assets/fonts/Rowdies-Light.ttf
        - asset: assets/fonts/Rowdies-Bold.ttf

    - family: BalooBhaijaan2
      fonts:
        - asset: assets/fonts/BalooBhaijaan2-Regular.ttf
        - asset: assets/fonts/BalooBhaijaan2-SemiBold.ttf
        - asset: assets/fonts/BalooBhaijaan2-Medium.ttf
        - asset: assets/fonts/BalooBhaijaan2-ExtraBold.ttf
        - asset: assets/fonts/BalooBhaijaan2-Bold.ttf


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  #